IF object_id('TMKGroups','U') IS NULL EXEC('CREATE TABLE TMKGroups (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKGroups ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKGroups ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKGroups ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKGroups ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='GroupID') ALTER TABLE TMKGroups ADD [GroupID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='GroupName') ALTER TABLE TMKGroups ADD [GroupName] NVARCHAR(MAX) NOT NULL
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKGroups' AND COLUMN_NAME='nothing') ALTER TABLE TMKGroups DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKGroups') AND name = 'PK_TMKGroups') ALTER TABLE TMKGroups ADD CONSTRAINT PK_TMKGroups PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKGroups') AND name = 'IX_TMKGroups_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKGroups_ValidTo] ON [TMKGroups] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKGroups') AND name = 'IX_TMKGroups_GroupID') CREATE NONCLUSTERED INDEX [IX_TMKGroups_GroupID] ON [TMKGroups] (GroupID ASC)