IF object_id('TMKOrganizations','U') IS NULL EXEC('CREATE TABLE TMKOrganizations (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKOrganizations ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKOrganizations ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKOrganizations ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKOrganizations ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='OrganizationID') ALTER TABLE TMKOrganizations ADD [OrganizationID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='FullName') ALTER TABLE TMKOrganizations ADD [FullName] NVARCHAR(MAX) NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='ShortName') ALTER TABLE TMKOrganizations ADD [ShortName] NVARCHAR(MAX) NOT NULL
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKOrganizations' AND COLUMN_NAME='nothing') ALTER TABLE TMKOrganizations DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKOrganizations') AND name = 'PK_TMKOrganizations') ALTER TABLE TMKOrganizations ADD CONSTRAINT PK_TMKOrganizations PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKOrganizations') AND name = 'IX_TMKOrganizations_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKOrganizations_ValidTo] ON [TMKOrganizations] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKOrganizations') AND name = 'IX_TMKOrganizations_OrganizationID') CREATE NONCLUSTERED INDEX [IX_TMKOrganizations_OrganizationID] ON [TMKOrganizations] (OrganizationID ASC)