IF object_id('TMKTicketComments','U') IS NULL EXEC('CREATE TABLE TMKTicketComments (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKTicketComments ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKTicketComments ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKTicketComments ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKTicketComments ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='TicketID') ALTER TABLE TMKTicketComments ADD [TicketID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='CommentText') ALTER TABLE TMKTicketComments ADD [CommentText] NVARCHAR(MAX) NULL
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketComments' AND COLUMN_NAME='nothing') ALTER TABLE TMKTicketComments DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKTicketComments') AND name = 'PK_TMKTicketComments') ALTER TABLE TMKTicketComments ADD CONSTRAINT PK_TMKTicketComments PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKTicketComments') AND name = 'IX_TMKTicketComments_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKTicketComments_ValidTo] ON [TMKTicketComments] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKTicketComments') AND name = 'IX_TMKTicketComments_TicketID') CREATE NONCLUSTERED INDEX [IX_TMKTicketComments_TicketID] ON [TMKTicketComments] (TicketID ASC)