IF object_id('TMKTicketWork','U') IS NULL EXEC('CREATE TABLE TMKTicketWork (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKTicketWork ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKTicketWork ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKTicketWork ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKTicketWork ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='TicketID') ALTER TABLE TMKTicketWork ADD [TicketID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='UserID') ALTER TABLE TMKTicketWork ADD [UserID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='StartedAt') ALTER TABLE TMKTicketWork ADD [StartedAt] DATETIME NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='FinishedAt') ALTER TABLE TMKTicketWork ADD [FinishedAt] DATETIME NULL
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKTicketWork' AND COLUMN_NAME='nothing') ALTER TABLE TMKTicketWork DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKTicketWork') AND name = 'PK_TMKTicketWork') ALTER TABLE TMKTicketWork ADD CONSTRAINT PK_TMKTicketWork PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKTicketWork') AND name = 'IX_TMKTicketWork_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKTicketWork_ValidTo] ON [TMKTicketWork] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKTicketWork') AND name = 'IX_TMKTicketWork_TicketID') CREATE NONCLUSTERED INDEX [IX_TMKTicketWork_TicketID] ON [TMKTicketWork] (TicketID ASC)