IF object_id('TMKUserToGroup','U') IS NULL EXEC('CREATE TABLE TMKUserToGroup (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKUserToGroup ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKUserToGroup ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKUserToGroup ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKUserToGroup ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='UserID') ALTER TABLE TMKUserToGroup ADD [UserID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='GroupID') ALTER TABLE TMKUserToGroup ADD [GroupID] INT NOT NULL
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUserToGroup' AND COLUMN_NAME='nothing') ALTER TABLE TMKUserToGroup DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKUserToGroup') AND name = 'PK_TMKUserToGroup') ALTER TABLE TMKUserToGroup ADD CONSTRAINT PK_TMKUserToGroup PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKUserToGroup') AND name = 'IX_TMKUserToGroup_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKUserToGroup_ValidTo] ON [TMKUserToGroup] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKUserToGroup') AND name = 'IX_TMKUserToGroup_UserID') CREATE NONCLUSTERED INDEX [IX_TMKUserToGroup_UserID] ON [TMKUserToGroup] (UserID ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKUserToGroup') AND name = 'IX_TMKUserToGroup_GroupID') CREATE NONCLUSTERED INDEX [IX_TMKUserToGroup_GroupID] ON [TMKUserToGroup] (GroupID ASC)