IF object_id('TMKUsers','U') IS NULL EXEC('CREATE TABLE TMKUsers (nothing int)')
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='PrimaryID') ALTER TABLE TMKUsers ADD [PrimaryID] INT IDENTITY(1,1) NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='ValidFrom') ALTER TABLE TMKUsers ADD [ValidFrom] DATETIME NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='ValidTo') ALTER TABLE TMKUsers ADD [ValidTo] DATETIME NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='OwnerID') ALTER TABLE TMKUsers ADD [OwnerID] BIGINT NOT NULL 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='UserID') ALTER TABLE TMKUsers ADD [UserID] INT NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='UserFullName') ALTER TABLE TMKUsers ADD [UserFullName] NVARCHAR(MAX) NOT NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='IsRequester') ALTER TABLE TMKUsers ADD [IsRequester] BIT NOT NULL DEFAULT(0)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='IsWorker') ALTER TABLE TMKUsers ADD [IsWorker] BIT NOT NULL DEFAULT(0)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='EmailAddress') ALTER TABLE TMKUsers ADD [EmailAddress] NVARCHAR(MAX) NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='HashedPassword') ALTER TABLE TMKUsers ADD [HashedPassword] NVARCHAR(32) NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='Salt') ALTER TABLE TMKUsers ADD [Salt] NVARCHAR(32) NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='PasswordExpiry') ALTER TABLE TMKUsers ADD [PasswordExpiry] DATETIME NOT NULL DEFAULT (DATEADD(year, 2, getdate()))
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TMKUsers' AND COLUMN_NAME='nothing') ALTER TABLE TMKUsers DROP COLUMN nothing
IF NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('TMKUsers') AND name = 'PK_TMKUsers') ALTER TABLE TMKUsers ADD CONSTRAINT PK_TMKUsers PRIMARY KEY  CLUSTERED (PrimaryID ASC)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKUsers') AND name = 'IX_TMKUsers_ValidTo') CREATE NONCLUSTERED INDEX [IX_TMKUsers_ValidTo] ON [TMKUsers] (ValidTo ASC)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('TMKUsers') AND name = 'IX_TMKUsers_UserID') CREATE NONCLUSTERED INDEX [IX_TMKUsers_UserID] ON [TMKUsers] (UserID ASC)